### ISSUE TITLE
Too many buckets

### ISSUE THREAD

**Issue by atkinsonm** [melusom/CSC470-Cloud-Project#43]
I got a "Too many buckets" error from AWS. Probably a good thing considering we created over 100 test buckets, but we should clean out the ones that we aren't using. Now that we are testing with uploaded files, you may need an updated bucket deletion program.

**Comment by bgottlob** [comment]
I just ran the script so you can continue working. I'll update this to delete all of the objects in the buckets, then all the buckets so S3 will be completely cleared.

**Comment by atkinsonm** [comment]
No problem, I'm actually done testing this module anyway
